import type { Sex, Structure } from "./types";

/**
 * Every clickable structure in the figure.
 *
 * `at` is the approximate centre in the body viewBox (0 0 420 1000), midline
 * x = 210. Remember this is an anterior view: the subject's right side is on
 * the LEFT of the image, which is why the liver sits at x < 210.
 */
export const STRUCTURES: Structure[] = [
  // ───────────────────────────── SKIN ─────────────────────────────
  {
    id: "skin",
    layer: "skin",
    group: "integumentary",
    at: [150, 340],
    labelSide: "left",
    name: { en: "Skin", da: "Hud" },
    latin: "Cutis",
    description: {
      en: "Your largest organ, and a waterproof coat you never take off. It keeps water and warmth in, keeps germs out, and is packed with sensors for touch, pressure, heat and pain.",
      da: "Dit største organ og en vandtæt jakke, du aldrig tager af. Den holder på vand og varme, holder bakterier ude og er fyldt med følere for berøring, tryk, varme og smerte.",
    },
    fact: {
      en: "Spread flat, an adult's skin would cover about 2 m² and weigh around 4 kg. You shed roughly 500 million skin cells a day.",
      da: "Bredt fladt ud dækker en voksens hud omkring 2 m² og vejer cirka 4 kg. Du taber omkring 500 millioner hudceller om dagen.",
    },
  },
  {
    id: "melanin",
    layer: "skin",
    group: "integumentary",
    at: [268, 300],
    labelSide: "right",
    name: { en: "Skin pigment", da: "Hudpigment" },
    latin: "Melanin",
    description: {
      en: "Cells in the epidermis called melanocytes make melanin, the pigment that gives skin, hair and eyes their colour and soaks up ultraviolet light from the sun.",
      da: "Celler i overhuden kaldet melanocytter danner melanin — det farvestof, der giver hud, hår og øjne deres farve og opsuger ultraviolet lys fra solen.",
    },
    fact: {
      en: "Everyone has almost the same number of melanocytes. What differs is how much melanin they make — and nothing beneath the skin differs at all.",
      da: "Alle har næsten lige mange melanocytter. Det, der er forskelligt, er hvor meget melanin de laver — og under huden er der slet ingen forskel.",
    },
  },
  {
    id: "hair",
    layer: "skin",
    group: "integumentary",
    at: [210, 44],
    labelSide: "right",
    name: { en: "Hair", da: "Hår" },
    latin: "Pilus",
    description: {
      en: "Each hair is a rope of dead, hardened cells pushed up out of a living follicle in the dermis. Hair traps warmth and, on the head, shields the scalp from sunlight.",
      da: "Hvert hår er et reb af døde, hårde celler, der skubbes op fra en levende hårsæk i læderhuden. Hår holder på varmen og skærmer hovedbunden mod sollys.",
    },
    fact: {
      en: "Scalp hair grows about 1 cm a month and you have roughly 100,000 of them. Whether a hair is straight or curly depends on the shape of its follicle.",
      da: "Hovedhår vokser cirka 1 cm om måneden, og du har omkring 100.000 af dem. Om et hår er glat eller krøllet afhænger af hårsækkens form.",
    },
  },
  {
    id: "eye-surface",
    layer: "skin",
    group: "sensory",
    at: [188, 92],
    labelSide: "left",
    name: { en: "Eye", da: "Øje" },
    latin: "Oculus",
    description: {
      en: "A fluid-filled ball about 2.5 cm across. Light passes the cornea and lens, which focus it onto the retina at the back, where 126 million light sensors turn it into nerve signals.",
      da: "En væskefyldt kugle på cirka 2,5 cm. Lys passerer hornhinden og linsen, der samler det på nethinden bagest, hvor 126 millioner lysfølere laver det om til nervesignaler.",
    },
    fact: {
      en: "Your eyes flick about three times a second in tiny jumps called saccades. Your brain edits out the blur so the world looks steady.",
      da: "Dine øjne springer omkring tre gange i sekundet i små ryk kaldet sakkader. Hjernen klipper sløret væk, så verden ser rolig ud.",
    },
  },
  {
    id: "ear",
    layer: "skin",
    group: "sensory",
    at: [162, 106],
    labelSide: "left",
    name: { en: "Ear", da: "Øre" },
    latin: "Auris",
    description: {
      en: "The flap you can see funnels sound into a canal ending at the eardrum. Behind it, three tiny bones pass the vibration to the fluid-filled cochlea, which reads it as sound.",
      da: "Den flap, du kan se, leder lyd ind i en kanal, der ender ved trommehinden. Bagved sender tre bittesmå knogler svingningen videre til den væskefyldte sneglegang, der tolker den som lyd.",
    },
    fact: {
      en: "The stapes in your middle ear is the smallest bone in the body — about 3 mm, no bigger than a grain of rice.",
      da: "Stigbøjlen i mellemøret er kroppens mindste knogle — cirka 3 mm, ikke større end et riskorn.",
    },
  },
  {
    id: "nose",
    layer: "skin",
    group: "respiratory",
    at: [204, 118],
    labelSide: "right",
    name: { en: "Nose", da: "Næse" },
    latin: "Nasus",
    description: {
      en: "Air's front door. The nose warms, moistens and filters every breath, and its roof carries a patch of smell sensors wired straight into the brain.",
      da: "Luftens hoveddør. Næsen varmer, fugter og filtrerer hvert åndedrag, og i dens loft sidder et felt af lugtsansere, der er koblet direkte til hjernen.",
    },
    fact: {
      en: "You can tell apart something like a trillion different smells — far more than the number of colours you can see.",
      da: "Du kan skelne omkring en billion forskellige lugte — langt flere end antallet af farver, du kan se.",
    },
  },
  {
    id: "nail",
    layer: "skin",
    group: "integumentary",
    at: [128, 512],
    labelSide: "left",
    name: { en: "Nails", da: "Negle" },
    latin: "Unguis",
    description: {
      en: "Plates of hard keratin that shield your fingertips and give them something to press against, which is what makes fine touch and picking things up possible.",
      da: "Plader af hård keratin, der beskytter fingerspidserne og giver dem noget at presse imod — det er derfor, du kan mærke fint og gribe ting.",
    },
    fact: {
      en: "Fingernails grow about 3 mm a month, roughly four times faster than toenails. Your middle fingernail grows fastest of all.",
      da: "Fingernegle vokser cirka 3 mm om måneden — omkring fire gange hurtigere end tånegle. Langfingerens negl vokser hurtigst.",
    },
  },
  {
    id: "navel",
    layer: "skin",
    group: "integumentary",
    at: [210, 392],
    labelSide: "right",
    name: { en: "Navel", da: "Navle" },
    latin: "Umbilicus",
    description: {
      en: "The scar left where the umbilical cord once carried oxygen and food from the placenta into your bloodstream before you were born.",
      da: "Arret hvor navlestrengen engang førte ilt og næring fra moderkagen ind i dit blod, før du blev født.",
    },
    fact: {
      en: "It's the one scar every single human being has.",
      da: "Det er det ene ar, som hvert eneste menneske har.",
    },
  },

  // ─────────────────────────── MUSCLES ───────────────────────────
  {
    id: "sternocleidomastoid",
    layer: "muscles",
    group: "muscular",
    at: [188, 172],
    labelSide: "left",
    name: { en: "Neck turner", da: "Nikkemuskel" },
    latin: "Sternocleidomastoideus",
    description: {
      en: "A long strap running from behind the ear down to the collarbone and breastbone. One side turns your head; both together pull your chin to your chest.",
      da: "En lang rem, der løber fra bag øret ned til kravebenet og brystbenet. Én side drejer hovedet; begge sammen trækker hagen ned mod brystet.",
    },
    fact: {
      en: "Nod 'yes' and you use the deep neck muscles; shake 'no' and this is the one doing the work.",
      da: "Nikker du 'ja', bruger du de dybe halsmuskler; ryster du på hovedet, er det denne, der arbejder.",
    },
  },
  {
    id: "trapezius",
    layer: "muscles",
    group: "muscular",
    at: [150, 206],
    labelSide: "left",
    name: { en: "Trapezius", da: "Kappemuskel" },
    latin: "Trapezius",
    description: {
      en: "A big diamond-shaped sheet across the upper back and shoulders. It shrugs your shoulders, steadies the shoulder blades and helps tilt your head back.",
      da: "En stor rudeformet plade over den øverste ryg og skuldrene. Den trækker på skuldrene, stabiliserer skulderbladene og hjælper med at bøje hovedet bagover.",
    },
    fact: {
      en: "Carry a heavy bag on one shoulder and this is the muscle that aches afterwards.",
      da: "Bær en tung taske på én skulder — det er denne muskel, der gør ondt bagefter.",
    },
  },
  {
    id: "deltoid",
    layer: "muscles",
    group: "muscular",
    at: [118, 230],
    labelSide: "left",
    name: { en: "Deltoid", da: "Deltamuskel" },
    latin: "Deltoideus",
    description: {
      en: "The rounded cap of the shoulder, named after the triangular Greek letter delta. It lifts the arm out sideways, forwards and backwards.",
      da: "Skulderens runde kappe, opkaldt efter det trekantede græske bogstav delta. Den løfter armen ud til siden, frem og tilbage.",
    },
    fact: {
      en: "It's the usual spot for a vaccination — thick enough for the needle, close enough to lymph vessels to spread the response fast.",
      da: "Det er det sædvanlige sted for en vaccination — tyk nok til nålen og tæt nok på lymfekar til at sprede reaktionen hurtigt.",
    },
  },
  {
    id: "pectoralis-major",
    layer: "muscles",
    group: "muscular",
    at: [172, 268],
    labelSide: "left",
    name: { en: "Chest muscle", da: "Brystmuskel" },
    latin: "Pectoralis major",
    description: {
      en: "A broad fan across the front of the chest, anchored to the breastbone and ribs and pulling on the upper arm. It drags the arm forwards and across the body.",
      da: "En bred vifte hen over brystets forside, forankret i brystben og ribben og med træk i overarmen. Den trækker armen frem og ind foran kroppen.",
    },
    fact: {
      en: "It's the muscle doing the work in a push-up, a hug, and a swimmer's front-crawl pull.",
      da: "Det er den muskel, der arbejder i en armbøjning, et kram og svømmerens crawltag.",
    },
  },
  {
    id: "biceps",
    layer: "muscles",
    group: "muscular",
    at: [110, 330],
    labelSide: "left",
    name: { en: "Biceps", da: "Bicepsmuskel" },
    latin: "Biceps brachii",
    description: {
      en: "The bulge on the front of the upper arm. Its name means 'two heads' because it starts as two tendons. It bends the elbow and twists the palm face-up.",
      da: "Bulen på overarmens forside. Navnet betyder 'to hoveder', fordi den starter som to sener. Den bøjer albuen og drejer håndfladen opad.",
    },
    fact: {
      en: "Muscles can only pull, never push. That's why the biceps needs the triceps behind it to straighten the arm again.",
      da: "Muskler kan kun trække, aldrig skubbe. Derfor har bicepsen brug for tricepsen bagved til at strække armen ud igen.",
    },
  },
  {
    id: "triceps",
    layer: "muscles",
    group: "muscular",
    at: [138, 330],
    labelSide: "right",
    name: { en: "Triceps", da: "Tricepsmuskel" },
    latin: "Triceps brachii",
    description: {
      en: "The three-headed muscle down the back of the upper arm. It is the biceps' opposite number: where the biceps bends the elbow, the triceps straightens it.",
      da: "Den trehovedede muskel på bagsiden af overarmen. Den er bicepsens modspiller: hvor bicepsen bøjer albuen, strækker tricepsen den.",
    },
    fact: {
      en: "Muscles nearly always work in opposing pairs — as one shortens, its partner has to relax and stretch.",
      da: "Muskler arbejder næsten altid i modsatte par — når den ene trækker sig sammen, må makkeren slappe af og strækkes.",
    },
  },
  {
    id: "forearm-flexors",
    layer: "muscles",
    group: "muscular",
    at: [118, 428],
    labelSide: "left",
    name: { en: "Forearm flexors", da: "Underarmens bøjemuskler" },
    latin: "Flexores antebrachii",
    description: {
      en: "A bundle of muscles in the forearm whose long tendons run through the wrist to the fingers. Your fingers have almost no muscle in them — they're worked by remote control.",
      da: "En bundt muskler i underarmen, hvis lange sener løber gennem håndleddet ud til fingrene. Fingrene har næsten ingen muskler — de styres på afstand.",
    },
    fact: {
      en: "Wiggle your fingers while holding your forearm and you can feel the muscles that are actually moving them.",
      da: "Vrik med fingrene, mens du holder om underarmen — så kan du mærke de muskler, der faktisk bevæger dem.",
    },
  },
  {
    id: "rectus-abdominis",
    layer: "muscles",
    group: "muscular",
    at: [210, 360],
    labelSide: "right",
    name: { en: "Abdominal muscle", da: "Lige bugmuskel" },
    latin: "Rectus abdominis",
    description: {
      en: "A strap running straight down the belly from ribs to pubic bone, crossed by bands of tendon that divide it into the blocks people call a six-pack. It curls the trunk forwards.",
      da: "En rem, der løber lige ned over maven fra ribben til skambenet, krydset af senebånd, som deler den i de blokke, man kalder en sixpack. Den bøjer kroppen fremad.",
    },
    fact: {
      en: "The 'six-pack' is not something you build — everyone already has it. It only shows when there's little fat over the top.",
      da: "En 'sixpack' er ikke noget, man bygger — alle har den allerede. Den ses kun, når der er lidt fedt henover.",
    },
  },
  {
    id: "external-oblique",
    layer: "muscles",
    group: "muscular",
    at: [168, 372],
    labelSide: "left",
    name: { en: "External oblique", da: "Ydre skrå bugmuskel" },
    latin: "Obliquus externus abdominis",
    description: {
      en: "A sheet whose fibres run diagonally down and forwards across the side of the abdomen, like hands going into pockets. It twists and bends the trunk sideways.",
      da: "En plade, hvis fibre løber skråt nedad og fremad hen over maven — som hænder på vej i lommen. Den vrider og bøjer kroppen til siden.",
    },
    fact: {
      en: "Layers of abdominal muscle run in different directions, like plywood. That crossing is what makes the belly wall strong without bone.",
      da: "Lagene af bugmuskler løber i hver sin retning, ligesom krydsfiner. Netop krydset gør bugvæggen stærk uden knogler.",
    },
  },
  {
    id: "gluteus",
    layer: "muscles",
    group: "muscular",
    at: [140, 462],
    labelSide: "left",
    name: { en: "Gluteal muscles", da: "Ballemuskler" },
    latin: "Gluteus maximus / medius",
    description: {
      en: "The muscles of the buttock — the bulkiest in the body. They drive the hip backwards when you stand up, climb or run, and hold your pelvis level as you walk.",
      da: "Ballens muskler — kroppens kraftigste. De driver hoften bagud, når du rejser dig, går på trapper eller løber, og holder bækkenet vandret, når du går.",
    },
    fact: {
      en: "Powerful glutes are a hallmark of walking upright. No other animal has a backside quite like ours.",
      da: "Stærke ballemuskler er et kendetegn ved at gå oprejst. Intet andet dyr har en bagdel helt som vores.",
    },
  },
  {
    id: "quadriceps",
    layer: "muscles",
    group: "muscular",
    at: [168, 596],
    labelSide: "left",
    name: { en: "Quadriceps", da: "Firhovedet lårmuskel" },
    latin: "Quadriceps femoris",
    description: {
      en: "Four muscles on the front of the thigh that join into one tendon over the kneecap. Together they straighten the knee — the strongest muscle group you have.",
      da: "Fire muskler på lårets forside, som løber sammen i én sene over knæskallen. Sammen strækker de knæet — din stærkeste muskelgruppe.",
    },
    fact: {
      en: "Tap the tendon just under your kneecap and the leg kicks by itself. The signal never reaches your brain — it turns around in the spinal cord.",
      da: "Bank på senen lige under knæskallen, og benet sparker af sig selv. Signalet når aldrig hjernen — det vender om i rygmarven.",
    },
  },
  {
    id: "sartorius",
    layer: "muscles",
    group: "muscular",
    at: [188, 552],
    labelSide: "right",
    name: { en: "Tailor's muscle", da: "Skræddermuskel" },
    latin: "Sartorius",
    description: {
      en: "The longest muscle in the body, a thin ribbon spiralling from the hip bone across the thigh to the inside of the knee. It lifts and turns the thigh outwards.",
      da: "Kroppens længste muskel — et tyndt bånd, der snor sig fra hoftebenet skråt over låret til indersiden af knæet. Den løfter og drejer låret udad.",
    },
    fact: {
      en: "Its name comes from sartor, Latin for tailor: it puts your legs into the cross-legged position tailors once worked in.",
      da: "Navnet kommer af sartor, latin for skrædder: den sætter benene i den skrædderstilling, skræddere før i tiden sad og arbejdede i.",
    },
  },
  {
    id: "gastrocnemius",
    layer: "muscles",
    group: "muscular",
    at: [158, 762],
    labelSide: "left",
    name: { en: "Calf muscle", da: "Lægmuskel" },
    latin: "Gastrocnemius",
    description: {
      en: "The two-headed bulge of the calf. It joins the soleus beneath it to form the Achilles tendon, and pushes your heel down every time you take a step or jump.",
      da: "Læggens tohovedede bule. Den løber sammen med sålemusklen nedenunder i akillessenen og presser hælen ned, hver gang du tager et skridt eller hopper.",
    },
    fact: {
      en: "The Achilles tendon is the body's thickest and can take a load of more than half a tonne when you sprint.",
      da: "Akillessenen er kroppens tykkeste og kan tage en belastning på over et halvt ton, når du spurter.",
    },
  },
  {
    id: "tibialis-anterior",
    layer: "muscles",
    group: "muscular",
    at: [192, 790],
    labelSide: "right",
    name: { en: "Shin muscle", da: "Forreste skinnebensmuskel" },
    latin: "Tibialis anterior",
    description: {
      en: "Runs down the outer side of the shin bone and pulls the foot upwards. Without it your toes would catch the ground on every stride.",
      da: "Løber ned langs ydersiden af skinnebenet og trækker foden opad. Uden den ville tæerne hænge fast i jorden ved hvert skridt.",
    },
    fact: {
      en: "Walk on your heels for a few seconds and the burning you feel at the front of the shin is this muscle.",
      da: "Gå på hælene i nogle sekunder — den brænden, du mærker foran på skinnebenet, er denne muskel.",
    },
  },
  {
    id: "facial-muscles",
    layer: "muscles",
    group: "muscular",
    at: [232, 76],
    labelSide: "right",
    name: { en: "Facial muscles", da: "Ansigtsmuskler" },
    latin: "Musculi faciales",
    description: {
      en: "More than forty small muscles that attach to the skin of the face rather than to bone. Pulling on the skin directly is what lets you make expressions.",
      da: "Over fyrre små muskler, der hæfter i ansigtets hud i stedet for i knogler. Netop fordi de trækker direkte i huden, kan du lave ansigtsudtryk.",
    },
    fact: {
      en: "A genuine smile also tightens the muscle around the eye, and that part is very hard to fake — which is how a polite smile gives itself away.",
      da: "Et ægte smil strammer også musklen omkring øjet, og lige den del er meget svær at spille — sådan afslører et høfligt smil sig selv.",
    },
  },
  {
    id: "serratus",
    layer: "muscles",
    group: "muscular",
    at: [156, 300],
    labelSide: "left",
    name: { en: "Serratus anterior", da: "Forreste savtakkede muskel" },
    latin: "Serratus anterior",
    description: {
      en: "A muscle whose finger-like slips grip the ribs below the armpit. It slides the shoulder blade forwards and holds it flat against the ribcage.",
      da: "En muskel, hvis fingerlignende takker griber fat i ribbenene under armhulen. Den skubber skulderbladet fremad og holder det fladt mod brystkassen.",
    },
    fact: {
      en: "Boxers use it in every punch, which is why it's nicknamed the boxer's muscle.",
      da: "Boksere bruger den i hvert slag — derfor kaldes den bokserens muskel.",
    },
  },
  {
    id: "adductors",
    layer: "muscles",
    group: "muscular",
    at: [222, 540],
    labelSide: "right",
    name: { en: "Adductors", da: "Indadførende lårmuskler" },
    latin: "Musculi adductores",
    description: {
      en: "The group along the inner thigh that pulls the legs together. They also steady the pelvis with every step you take.",
      da: "Gruppen langs lårets inderside, der trækker benene sammen. De stabiliserer også bækkenet ved hvert skridt, du tager.",
    },
    fact: {
      en: "Squeeze your knees together and you can feel the whole group harden under your fingers.",
      da: "Pres knæene sammen, så kan du mærke hele gruppen blive hård under fingrene.",
    },
  },
  {
    id: "diaphragm",
    layer: "muscles",
    group: "respiratory",
    at: [210, 336],
    labelSide: "right",
    name: { en: "Diaphragm", da: "Mellemgulv" },
    latin: "Diaphragma",
    description: {
      en: "A domed sheet of muscle sealing the bottom of the chest. When it tightens it flattens downwards, the chest grows, and air is pulled into the lungs. This is breathing.",
      da: "En kuppelformet muskelplade, der lukker brystkassen nedadtil. Når den spænder, flader den ud nedad, brystkassen vokser, og luft suges ind i lungerne. Det er vejrtrækning.",
    },
    fact: {
      en: "A hiccup is the diaphragm twitching without warning; the 'hic' is your vocal cords snapping shut on the sudden rush of air.",
      da: "Hikke er mellemgulvet, der trækker sig sammen uden varsel; lyden er stemmelæberne, der smækker i om det pludselige luftsug.",
    },
  },

  // ─────────────────────────── ORGANS ───────────────────────────
  {
    id: "brain",
    layer: "organs",
    group: "nervous",
    at: [210, 82],
    labelSide: "right",
    name: { en: "Brain", da: "Hjerne" },
    latin: "Encephalon",
    description: {
      en: "The most complex object known. Some 86 billion neurons, wired into a network of trillions of connections, run your body, your senses, your memories and your sense of being you.",
      da: "Det mest komplekse, vi kender. Omkring 86 milliarder neuroner, koblet i et net af billioner af forbindelser, styrer din krop, dine sanser, dine minder og din fornemmelse af at være dig.",
    },
    fact: {
      en: "The brain is about 2% of your body weight but takes 20% of your energy — it burns power like a small light bulb, day and night.",
      da: "Hjernen udgør cirka 2 % af din kropsvægt, men bruger 20 % af din energi — den bruger strøm som en lille pære, døgnet rundt.",
    },
  },
  {
    id: "heart",
    layer: "organs",
    group: "circulatory",
    at: [222, 300],
    labelSide: "right",
    name: { en: "Heart", da: "Hjerte" },
    latin: "Cor",
    description: {
      en: "A fist-sized double pump of muscle. Its right side sends used blood to the lungs for oxygen; its left side drives the freshly loaded blood out to every other cell in the body.",
      da: "En dobbeltpumpe af muskel på størrelse med din knytnæve. Højre side sender brugt blod til lungerne efter ilt; venstre side driver det friske blod ud til alle andre celler i kroppen.",
    },
    fact: {
      en: "It beats around 100,000 times a day and about 2.5 billion times in a lifetime, without ever taking a break.",
      da: "Det slår omkring 100.000 gange i døgnet og cirka 2,5 milliarder gange i et liv — uden nogensinde at holde pause.",
    },
  },
  {
    id: "lungs",
    layer: "organs",
    group: "respiratory",
    at: [168, 288],
    labelSide: "left",
    name: { en: "Lungs", da: "Lunger" },
    latin: "Pulmones",
    description: {
      en: "Two soft, spongy bags of branching tubes ending in about 300 million tiny air sacs. Oxygen crosses their walls into the blood, and carbon dioxide crosses back out.",
      da: "To bløde, svampede poser af forgrenede rør, der ender i omkring 300 millioner bittesmå luftblærer. Ilt går gennem deres vægge ind i blodet, og kuldioxid går den anden vej.",
    },
    fact: {
      en: "Unfolded, the air sacs would carpet half a tennis court — all packed inside your chest.",
      da: "Foldet ud ville luftblærerne dække en halv tennisbane — alt sammen pakket ned i din brystkasse.",
    },
  },
  {
    id: "trachea",
    layer: "organs",
    group: "respiratory",
    at: [210, 212],
    labelSide: "right",
    name: { en: "Windpipe", da: "Luftrør" },
    latin: "Trachea",
    description: {
      en: "The tube from throat to lungs, held permanently open by C-shaped rings of cartilage. Its lining sweeps dust and mucus back up towards the throat.",
      da: "Røret fra svælget til lungerne, holdt permanent åbent af C-formede bruskringe. Slimhinden fejer støv og slim tilbage op mod svælget.",
    },
    fact: {
      en: "The rings are open at the back so the gullet behind can bulge as food goes down.",
      da: "Ringene er åbne bagtil, så spiserøret bagved kan bule ud, når maden glider ned.",
    },
  },
  {
    id: "liver",
    layer: "organs",
    group: "digestive",
    at: [176, 352],
    labelSide: "left",
    name: { en: "Liver", da: "Lever" },
    latin: "Hepar",
    description: {
      en: "The body's chemical works and its largest internal organ. It processes everything absorbed from the gut, stores sugars and vitamins, breaks down poisons and makes bile.",
      da: "Kroppens kemiske fabrik og dens største indre organ. Den bearbejder alt, hvad tarmen optager, lagrer sukker og vitaminer, nedbryder gifte og danner galde.",
    },
    fact: {
      en: "The liver performs over 500 different jobs, and it is the only human organ that can regrow itself after part of it is removed.",
      da: "Leveren udfører over 500 forskellige opgaver og er det eneste menneskelige organ, der kan vokse ud igen, når en del er fjernet.",
    },
  },
  {
    id: "stomach",
    layer: "organs",
    group: "digestive",
    at: [246, 366],
    labelSide: "right",
    name: { en: "Stomach", da: "Mavesæk" },
    latin: "Gaster",
    description: {
      en: "A muscular bag that churns food with acid strong enough to dissolve metal, turning a meal into a soup called chyme before it passes on to the intestine.",
      da: "En muskuløs pose, der ælter maden sammen med syre stærk nok til at opløse metal og gør måltidet til en suppe kaldet chymus, før det sendes videre til tarmen.",
    },
    fact: {
      en: "Its lining is replaced every few days — otherwise the stomach would digest itself.",
      da: "Slimhinden udskiftes hver få dage — ellers ville mavesækken fordøje sig selv.",
    },
  },
  {
    id: "small-intestine",
    layer: "organs",
    group: "digestive",
    at: [210, 428],
    labelSide: "right",
    name: { en: "Small intestine", da: "Tyndtarm" },
    latin: "Intestinum tenue",
    description: {
      en: "Six metres of coiled tube where digestion finishes and nutrients are absorbed. Its lining is folded and covered in millions of tiny fingers called villi.",
      da: "Seks meter sammenrullet rør, hvor fordøjelsen fuldføres og næringsstofferne optages. Slimhinden er foldet og dækket af millioner af små fingre kaldet villi.",
    },
    fact: {
      en: "All that folding gives it a surface area of around 250 m² — about the size of a tennis court.",
      da: "Al den foldning giver et overfladeareal på omkring 250 m² — cirka en tennisbane.",
    },
  },
  {
    id: "large-intestine",
    layer: "organs",
    group: "digestive",
    at: [156, 410],
    labelSide: "left",
    name: { en: "Large intestine", da: "Tyktarm" },
    latin: "Intestinum crassum",
    description: {
      en: "A wide frame around the small intestine. It reclaims water and salts from what's left, and houses the trillions of bacteria that finish the job.",
      da: "En bred ramme omkring tyndtarmen. Den henter vand og salte tilbage fra resterne og huser de billioner af bakterier, der gør arbejdet færdigt.",
    },
    fact: {
      en: "You carry roughly as many bacterial cells as human cells. Most of them live here.",
      da: "Du bærer rundt på omtrent lige så mange bakterieceller som menneskeceller. De fleste af dem bor her.",
    },
  },
  {
    id: "kidneys",
    layer: "organs",
    group: "urinary",
    at: [178, 386],
    labelSide: "left",
    name: { en: "Kidneys", da: "Nyrer" },
    latin: "Renes",
    description: {
      en: "Two bean-shaped filters, each holding a million tiny units called nephrons. They clean the blood, balance its water and salt, and send the waste onward as urine.",
      da: "To bønneformede filtre, der hver rummer en million små enheder kaldet nefroner. De renser blodet, styrer dets vand og salt og sender affaldet videre som urin.",
    },
    fact: {
      en: "Your kidneys filter your entire blood volume about 40 times a day — around 180 litres, of which all but 1.5 litres is reclaimed.",
      da: "Nyrerne filtrerer hele din blodmængde omkring 40 gange i døgnet — cirka 180 liter, hvoraf alt på nær 1,5 liter hentes tilbage.",
    },
  },
  {
    id: "bladder",
    layer: "organs",
    group: "urinary",
    at: [210, 464],
    labelSide: "right",
    name: { en: "Bladder", da: "Blære" },
    latin: "Vesica urinaria",
    description: {
      en: "A stretchy muscular reservoir for urine. As it fills, sensors in its wall report the pressure to the brain — which is how you know it's time to go.",
      da: "Et elastisk muskelreservoir til urin. Når den fyldes, melder følere i væggen trykket videre til hjernen — det er sådan, du ved, det er tid.",
    },
    fact: {
      en: "It holds about 400–600 ml comfortably, but the first urge arrives at around 200 ml.",
      da: "Den rummer behageligt 400–600 ml, men den første trang melder sig ved cirka 200 ml.",
    },
  },
  {
    id: "spleen",
    layer: "organs",
    group: "lymphatic",
    at: [262, 354],
    labelSide: "right",
    name: { en: "Spleen", da: "Milt" },
    latin: "Lien",
    description: {
      en: "A blood filter tucked behind the stomach. It pulls worn-out red blood cells out of circulation and holds a reserve of white cells ready to fight infection.",
      da: "Et blodfilter, der ligger bag mavesækken. Den fjerner udslidte røde blodlegemer fra kredsløbet og rummer et lager af hvide blodlegemer klar til at bekæmpe infektion.",
    },
    fact: {
      en: "Red blood cells last about 120 days. The spleen scraps around 2 million of them every second.",
      da: "Røde blodlegemer lever cirka 120 dage. Milten skrotter omkring 2 millioner af dem hvert sekund.",
    },
  },
  {
    id: "pancreas",
    layer: "organs",
    group: "digestive",
    at: [232, 378],
    labelSide: "right",
    name: { en: "Pancreas", da: "Bugspytkirtel" },
    latin: "Pancreas",
    description: {
      en: "A gland with two jobs at once: it pours digestive juices into the intestine, and it releases insulin straight into the blood to control blood sugar.",
      da: "En kirtel med to job på én gang: den hælder fordøjelsessaft ud i tarmen og sender insulin direkte i blodet for at styre blodsukkeret.",
    },
    fact: {
      en: "Only about 2% of the pancreas makes hormones. That tiny fraction is what fails in type 1 diabetes.",
      da: "Kun cirka 2 % af bugspytkirtlen laver hormoner. Netop den lille del svigter ved type 1-diabetes.",
    },
  },
  {
    id: "gallbladder",
    layer: "organs",
    group: "digestive",
    at: [190, 374],
    labelSide: "left",
    name: { en: "Gallbladder", da: "Galdeblære" },
    latin: "Vesica biliaris",
    description: {
      en: "A small green sac under the liver that stores and concentrates bile, then squirts it into the intestine when a fatty meal arrives.",
      da: "En lille grøn pose under leveren, der lagrer og koncentrerer galde og sprøjter den ud i tarmen, når et fedt måltid ankommer.",
    },
    fact: {
      en: "Bile works like washing-up liquid, breaking fat into droplets small enough for enzymes to attack.",
      da: "Galde virker som opvaskemiddel og deler fedt op i dråber, der er små nok til, at enzymer kan gå i gang.",
    },
  },
  {
    id: "esophagus",
    layer: "organs",
    group: "digestive",
    at: [204, 262],
    labelSide: "left",
    name: { en: "Gullet", da: "Spiserør" },
    latin: "Oesophagus",
    description: {
      en: "A muscular tube that doesn't just drop food — rings of muscle squeeze along it in waves, pushing each mouthful down to the stomach.",
      da: "Et muskelrør, der ikke bare lader maden falde — ringe af muskler klemmer i bølger nedad og skubber hver mundfuld ned i mavesækken.",
    },
    fact: {
      en: "Those waves are strong enough that you could swallow standing on your head.",
      da: "Bølgerne er så stærke, at du kunne synke, mens du stod på hovedet.",
    },
  },
  {
    id: "uterus",
    layer: "organs",
    group: "reproductive",
    sex: "female",
    at: [210, 446],
    labelSide: "right",
    name: { en: "Womb", da: "Livmoder" },
    latin: "Uterus",
    description: {
      en: "A thick-walled muscular chamber, normally about the size of a pear. In pregnancy it stretches to hold a full-grown baby and then contracts powerfully to deliver it.",
      da: "Et tykvægget muskelkammer, normalt på størrelse med en pære. Under graviditet strækker den sig og rummer et fuldbårent barn — og trækker sig så kraftigt sammen for at føde det.",
    },
    fact: {
      en: "It can grow to around 500 times its resting volume during pregnancy, then shrink back within weeks.",
      da: "Den kan vokse til cirka 500 gange sit hvilevolumen under graviditet og trække sig sammen igen på få uger.",
    },
  },
  {
    id: "ovaries",
    layer: "organs",
    group: "reproductive",
    sex: "female",
    at: [176, 440],
    labelSide: "left",
    name: { en: "Ovaries", da: "Æggestokke" },
    latin: "Ovaria",
    description: {
      en: "Two almond-sized glands that store egg cells and release one roughly every month, while producing the hormones oestrogen and progesterone.",
      da: "To mandelstore kirtler, der opbevarer ægceller og frigiver ét cirka hver måned, samtidig med at de producerer hormonerne østrogen og progesteron.",
    },
    fact: {
      en: "All the egg cells a person will ever have are already present before birth — about a million of them.",
      da: "Alle de ægceller, et menneske nogensinde får, findes allerede før fødslen — omkring en million.",
    },
  },
  {
    id: "testes",
    layer: "organs",
    group: "reproductive",
    sex: "male",
    at: [210, 486],
    labelSide: "right",
    name: { en: "Testes", da: "Testikler" },
    latin: "Testes",
    description: {
      en: "Two glands that make sperm cells and the hormone testosterone. They hang outside the body because sperm production needs to run a few degrees cooler than 37°C.",
      da: "To kirtler, der danner sædceller og hormonet testosteron. De hænger uden for kroppen, fordi sædproduktion kræver nogle grader mindre end 37 °C.",
    },
    fact: {
      en: "Inside each one is around 500 m of tightly coiled tubing where sperm cells are made — about 250 million a day.",
      da: "Inde i hver af dem er omkring 500 m tæt sammenrullet rør, hvor sædcellerne dannes — cirka 250 millioner om dagen.",
    },
  },
  {
    id: "prostate",
    layer: "organs",
    group: "reproductive",
    sex: "male",
    at: [210, 470],
    labelSide: "right",
    name: { en: "Prostate", da: "Blærehalskirtel" },
    latin: "Prostata",
    description: {
      en: "A walnut-sized gland wrapped around the urethra just below the bladder. It adds fluid that nourishes and activates sperm cells.",
      da: "En valnøddestor kirtel, der ligger som en krave om urinrøret lige under blæren. Den tilfører væske, som nærer og aktiverer sædcellerne.",
    },
    fact: {
      en: "It tends to enlarge with age, which is why it presses on the urethra in many older men.",
      da: "Den vokser typisk med alderen, og derfor trykker den på urinrøret hos mange ældre mænd.",
    },
  },

  // ────────────────────────── SKELETON ──────────────────────────
  {
    id: "skull",
    layer: "skeleton",
    group: "skeletal",
    at: [210, 84],
    labelSide: "right",
    name: { en: "Skull", da: "Kranium" },
    latin: "Cranium",
    description: {
      en: "Twenty-two bones, all but one locked together at jagged seams called sutures. The dome shields the brain; the front bones shape the face and hold the eyes.",
      da: "Toogtyve knogler, som alle på nær én er låst sammen i takkede sømme kaldet suturer. Kuplen beskytter hjernen; forreste knogler former ansigtet og holder øjnene.",
    },
    fact: {
      en: "A newborn's skull bones are not yet joined — the soft gaps let the head squeeze through the birth canal and the brain grow fast afterwards.",
      da: "Et nyfødt barns kranieknogler er endnu ikke vokset sammen — de bløde mellemrum lader hovedet presses gennem fødselskanalen og hjernen vokse hurtigt bagefter.",
    },
  },
  {
    id: "mandible",
    layer: "skeleton",
    group: "skeletal",
    at: [210, 144],
    labelSide: "left",
    name: { en: "Lower jaw", da: "Underkæbe" },
    latin: "Mandibula",
    description: {
      en: "The only skull bone that moves. It hinges just in front of the ear and carries the lower teeth, driven by the powerful chewing muscles at your temples and cheeks.",
      da: "Den eneste kranieknogle, der bevæger sig. Den hænger i et hængsel lige foran øret og bærer undertænderne, drevet af de kraftige tyggemuskler ved tindinger og kinder.",
    },
    fact: {
      en: "Your jaw muscles can bite with a force of about 70 kg on the back teeth — the strongest push, for its size, in the body.",
      da: "Dine kæbemuskler kan bide med en kraft på cirka 70 kg på kindtænderne — kroppens stærkeste tryk i forhold til størrelsen.",
    },
  },
  {
    id: "spine",
    layer: "skeleton",
    group: "skeletal",
    at: [210, 330],
    labelSide: "right",
    name: { en: "Spine", da: "Rygsøjle" },
    latin: "Columna vertebralis",
    description: {
      en: "Thirty-three vertebrae stacked in a gentle double curve, cushioned by discs of cartilage. It holds you upright, lets you bend and twist, and shields the spinal cord inside.",
      da: "Treogtredive hvirvler stablet i en blød dobbeltkurve og polstret af bruskskiver. Den holder dig oprejst, lader dig bøje og vride dig — og beskytter rygmarven indeni.",
    },
    fact: {
      en: "You're taller in the morning. The discs squash a centimetre or two over a day and swell again while you sleep.",
      da: "Du er højere om morgenen. Skiverne presses en centimeter eller to sammen i løbet af dagen og suger sig fulde igen, mens du sover.",
    },
  },
  {
    id: "ribs",
    layer: "skeleton",
    group: "skeletal",
    at: [162, 292],
    labelSide: "left",
    name: { en: "Ribs", da: "Ribben" },
    latin: "Costae",
    description: {
      en: "Twelve pairs of curved bones forming a cage around heart and lungs. They're hinged at the spine so the whole cage swings up and out with every breath in.",
      da: "Tolv par buede knogler, der danner et bur om hjerte og lunger. De er hængslet ved rygsøjlen, så hele buret svinger op og ud ved hvert indåndingstag.",
    },
    fact: {
      en: "The lowest two pairs attach to nothing at the front — they're called floating ribs.",
      da: "De to nederste par sidder ikke fast fortil — de kaldes flydende ribben.",
    },
  },
  {
    id: "sternum",
    layer: "skeleton",
    group: "skeletal",
    at: [210, 272],
    labelSide: "right",
    name: { en: "Breastbone", da: "Brystben" },
    latin: "Sternum",
    description: {
      en: "The flat blade down the centre of the chest. The upper seven pairs of ribs join it through springy cartilage, which is what lets the chest flex as you breathe.",
      da: "Den flade plade midt på brystet. De øverste syv ribbenspar hæfter til den gennem fjedrende brusk — det er derfor, brystkassen kan give sig, når du trækker vejret.",
    },
    fact: {
      en: "Its spongy interior is a lifelong blood-cell factory, which is why doctors sometimes sample marrow from here.",
      da: "Dens svampede indre er en livslang blodcellefabrik — derfor tager læger nogle gange knoglemarvsprøver her.",
    },
  },
  {
    id: "clavicle",
    layer: "skeleton",
    group: "skeletal",
    at: [162, 210],
    labelSide: "left",
    name: { en: "Collarbone", da: "Kraveben" },
    latin: "Clavicula",
    description: {
      en: "A slim S-shaped strut between breastbone and shoulder blade. It's the only bony link holding your arm onto the trunk, and it props the shoulder out sideways.",
      da: "En slank S-formet stiver mellem brystben og skulderblad. Den er den eneste knogleforbindelse, der holder armen fast på kroppen, og den skubber skulderen ud til siden.",
    },
    fact: {
      en: "Because it takes the impact of any fall onto an outstretched arm, it's the most commonly broken bone in the body.",
      da: "Fordi den optager stødet ved ethvert fald på udstrakt arm, er den kroppens hyppigst brækkede knogle.",
    },
  },
  {
    id: "scapula",
    layer: "skeleton",
    group: "skeletal",
    at: [150, 240],
    labelSide: "left",
    name: { en: "Shoulder blade", da: "Skulderblad" },
    latin: "Scapula",
    description: {
      en: "A flat triangular bone that floats on the back of the ribcage, held there by muscle alone. It carries the socket the upper arm bone sits in.",
      da: "En flad, trekantet knogle, der svæver på bagsiden af brystkassen, kun holdt på plads af muskler. Den bærer den skål, overarmsknoglen sidder i.",
    },
    fact: {
      en: "It's attached to the rest of the skeleton at just one small joint — where it meets the collarbone. Everything else is muscle.",
      da: "Den er kun fæstnet til resten af skelettet ét lille sted — dér hvor den møder kravebenet. Alt andet er muskler.",
    },
  },
  {
    id: "humerus",
    layer: "skeleton",
    group: "skeletal",
    at: [126, 318],
    labelSide: "left",
    name: { en: "Upper arm bone", da: "Overarmsknogle" },
    latin: "Humerus",
    description: {
      en: "The single long bone of the upper arm. Its ball-shaped head sits in a shallow socket on the shoulder blade — the loosest, and therefore most mobile, joint you have.",
      da: "Overarmens enlige lange knogle. Dens kugleformede hoved sidder i en flad skål på skulderbladet — dit løseste og dermed mest bevægelige led.",
    },
    fact: {
      en: "That shallow socket is a trade-off: it lets you swing your arm in a full circle, but it also means the shoulder dislocates more easily than any other joint.",
      da: "Den flade skål er et kompromis: du kan svinge armen hele vejen rundt, men skulderen går også lettere af led end noget andet led.",
    },
  },
  {
    id: "radius-ulna",
    layer: "skeleton",
    group: "skeletal",
    at: [118, 432],
    labelSide: "left",
    name: { en: "Forearm bones", da: "Underarmsknogler" },
    latin: "Radius & Ulna",
    description: {
      en: "Two bones side by side. The ulna forms the elbow's hinge; the radius rolls over it so you can turn your palm up and down without moving your elbow.",
      da: "To knogler side om side. Albuebenet danner albuens hængsel; spolebenet ruller hen over det, så du kan vende håndfladen op og ned uden at flytte albuen.",
    },
    fact: {
      en: "Turn your palm over while holding your forearm — you can feel the radius crossing over the ulna.",
      da: "Vend håndfladen om, mens du holder om underarmen — du kan mærke spolebenet krydse hen over albuebenet.",
    },
  },
  {
    id: "hand-bones",
    layer: "skeleton",
    group: "skeletal",
    at: [126, 496],
    labelSide: "left",
    name: { en: "Hand bones", da: "Håndens knogler" },
    latin: "Carpus, metacarpus, phalanges",
    description: {
      en: "Twenty-seven bones per hand: eight small blocks in the wrist, five in the palm and fourteen in the fingers. Together they make the most versatile tool in nature.",
      da: "Syvogtyve knogler i hver hånd: otte små blokke i håndleddet, fem i håndfladen og fjorten i fingrene. Sammen udgør de naturens mest alsidige værktøj.",
    },
    fact: {
      en: "A quarter of all the bones in your body are in your two hands.",
      da: "En fjerdedel af alle knogler i din krop sidder i dine to hænder.",
    },
  },
  {
    id: "pelvis",
    layer: "skeleton",
    group: "skeletal",
    at: [210, 436],
    labelSide: "right",
    name: { en: "Pelvis", da: "Bækken" },
    latin: "Pelvis",
    description: {
      en: "A basin of fused bone that carries the weight of your upper body down into your legs, anchors the hip joints and cradles the bladder and intestines.",
      da: "En skål af sammenvoksede knogler, der fører overkroppens vægt ned i benene, forankrer hofteleddene og bærer blære og tarme.",
    },
    fact: {
      en: "A female pelvis is typically wider and its opening rounder — the skeleton's clearest structural difference between the sexes.",
      da: "Et kvindeligt bækken er typisk bredere med en rundere åbning — skelettets tydeligste strukturelle kønsforskel.",
    },
  },
  {
    id: "femur",
    layer: "skeleton",
    group: "skeletal",
    at: [178, 578],
    labelSide: "left",
    name: { en: "Thigh bone", da: "Lårben" },
    latin: "Femur",
    description: {
      en: "The longest, heaviest and strongest bone you have — about a quarter of your height. Its ball head sits deep in the hip socket, angled inwards to bring your knees under your weight.",
      da: "Din længste, tungeste og stærkeste knogle — cirka en fjerdedel af din højde. Dens kuglehoved sidder dybt i hofteskålen og peger indad, så knæene kommer ind under din vægt.",
    },
    fact: {
      en: "Held upright, a femur can carry roughly 30 times an adult's body weight before it fails.",
      da: "Stillet lodret kan et lårben bære omkring 30 gange en voksens kropsvægt, før det giver efter.",
    },
  },
  {
    id: "patella",
    layer: "skeleton",
    group: "skeletal",
    at: [186, 676],
    labelSide: "right",
    name: { en: "Kneecap", da: "Knæskal" },
    latin: "Patella",
    description: {
      en: "A disc of bone that grew inside the quadriceps tendon. It rides in a groove on the femur and acts as a pulley, giving the thigh muscles more leverage on the shin.",
      da: "En knogleskive, der er vokset inde i quadricepssenen. Den glider i en rille på lårbenet og virker som en trisse, der giver lårmusklerne mere vægtstang på skinnebenet.",
    },
    fact: {
      en: "Without it, your thigh muscles would need about 30% more force to straighten the knee.",
      da: "Uden den skulle lårmusklerne bruge cirka 30 % mere kraft for at strække knæet.",
    },
  },
  {
    id: "tibia-fibula",
    layer: "skeleton",
    group: "skeletal",
    at: [178, 800],
    labelSide: "left",
    name: { en: "Shin bones", da: "Underbenets knogler" },
    latin: "Tibia & Fibula",
    description: {
      en: "The thick tibia carries essentially all your weight; the slender fibula beside it carries almost none, but anchors muscles and forms the outer bump of your ankle.",
      da: "Det tykke skinneben bærer stort set hele din vægt; det slanke lægben ved siden af bærer næsten ingenting, men forankrer muskler og danner anklens ydre knop.",
    },
    fact: {
      en: "The tibia's front edge lies right under the skin with no muscle over it — which is exactly why banging your shin hurts so much.",
      da: "Skinnebenets forkant ligger lige under huden uden muskel henover — derfor gør det så ondt at støde skinnebenet.",
    },
  },
  {
    id: "foot-bones",
    layer: "skeleton",
    group: "skeletal",
    at: [178, 936],
    labelSide: "left",
    name: { en: "Foot bones", da: "Fodens knogler" },
    latin: "Tarsus, metatarsus, phalanges",
    description: {
      en: "Twenty-six bones arranged into springy arches. They spread your weight, absorb the shock of each step and then push you off the ground again.",
      da: "Seksogtyve knogler samlet i fjedrende buer. De fordeler din vægt, optager stødet ved hvert skridt og skubber dig fra igen.",
    },
    fact: {
      en: "Walk a few kilometres and your feet absorb a load of several hundred tonnes in total.",
      da: "Gå nogle kilometer, og dine fødder optager en samlet belastning på flere hundrede tons.",
    },
  },
  {
    id: "bone-marrow",
    layer: "skeleton",
    group: "circulatory",
    at: [232, 578],
    labelSide: "right",
    name: { en: "Bone marrow", da: "Knoglemarv" },
    latin: "Medulla ossium",
    description: {
      en: "The soft tissue in the hollow core of large bones. Red marrow is a factory that turns out every red blood cell, white blood cell and platelet in your body.",
      da: "Det bløde væv i de store knoglers hule kerne. Rød marv er en fabrik, der producerer alle røde og hvide blodlegemer og blodplader i din krop.",
    },
    fact: {
      en: "It makes around 2 million red blood cells every second — about 170 billion a day.",
      da: "Den laver omkring 2 millioner røde blodlegemer i sekundet — cirka 170 milliarder om dagen.",
    },
  },

  // ─────────────────────── CIRCULATORY ───────────────────────
  {
    id: "aorta",
    layer: "circulatory",
    group: "circulatory",
    at: [216, 330],
    labelSide: "right",
    name: { en: "Aorta", da: "Aorta" },
    latin: "Aorta",
    description: {
      en: "The body's main artery and its largest blood vessel. It leaves the heart's left side, arches over, and runs down through the trunk giving off branches to everything.",
      da: "Kroppens hovedpulsåre og største blodkar. Den forlader hjertets venstre side, buer over og løber ned gennem kroppen med grene ud til alting.",
    },
    fact: {
      en: "It's about as thick as a garden hose, and its elastic wall stores energy from each heartbeat to keep the blood moving between beats.",
      da: "Den er cirka så tyk som en haveslange, og dens elastiske væg lagrer energi fra hvert hjerteslag, så blodet bliver ved med at strømme mellem slagene.",
    },
  },
  {
    id: "carotid",
    layer: "circulatory",
    group: "circulatory",
    at: [196, 176],
    labelSide: "left",
    name: { en: "Carotid artery", da: "Halspulsåre" },
    latin: "Arteria carotis",
    description: {
      en: "The artery running up each side of the neck to supply the brain. It carries a fifth of the heart's entire output straight to your head.",
      da: "Pulsåren, der løber op ad hver side af halsen og forsyner hjernen. Den fører en femtedel af hjertets samlede udpumpning direkte til hovedet.",
    },
    fact: {
      en: "Press two fingers gently beside your windpipe and you can feel it. Sensors in its wall constantly report your blood pressure to the brainstem.",
      da: "Læg to fingre let ved siden af luftrøret, så kan du mærke den. Følere i dens væg melder hele tiden dit blodtryk videre til hjernestammen.",
    },
  },
  {
    id: "vena-cava",
    layer: "circulatory",
    group: "circulatory",
    at: [200, 300],
    labelSide: "left",
    name: { en: "Vena cava", da: "Hulvene" },
    latin: "Vena cava",
    description: {
      en: "The two great veins that return oxygen-poor blood to the heart — one from the head and arms, one from everything below the diaphragm.",
      da: "De to store vener, der fører iltfattigt blod tilbage til hjertet — én fra hoved og arme, én fra alt under mellemgulvet.",
    },
    fact: {
      en: "Vein walls are thin and floppy because the pressure inside them is low. Valves stop the blood sliding backwards.",
      da: "Venernes vægge er tynde og slappe, fordi trykket i dem er lavt. Klapper forhindrer blodet i at glide baglæns.",
    },
  },
  {
    id: "pulmonary",
    layer: "circulatory",
    group: "circulatory",
    at: [232, 272],
    labelSide: "right",
    name: { en: "Pulmonary vessels", da: "Lungekar" },
    latin: "Arteria & vena pulmonalis",
    description: {
      en: "The short loop between heart and lungs. Uniquely, the pulmonary artery carries oxygen-poor blood and the pulmonary vein carries oxygen-rich blood — the reverse of everywhere else.",
      da: "Den korte sløjfe mellem hjerte og lunger. Enestående nok fører lungearterien iltfattigt blod og lungevenen iltrigt blod — modsat alle andre steder.",
    },
    fact: {
      en: "Blood makes the whole trip from heart to lungs and back in under ten seconds.",
      da: "Blodet klarer hele turen fra hjertet til lungerne og tilbage på under ti sekunder.",
    },
  },
  {
    id: "brachial-artery",
    layer: "circulatory",
    group: "circulatory",
    at: [128, 350],
    labelSide: "left",
    name: { en: "Brachial artery", da: "Overarmspulsåre" },
    latin: "Arteria brachialis",
    description: {
      en: "The main artery of the arm, running down the inner side of the upper arm before splitting at the elbow into the vessels that supply the forearm and hand.",
      da: "Armens hovedpulsåre, der løber ned ad overarmens inderside og deler sig ved albuen i de kar, der forsyner underarm og hånd.",
    },
    fact: {
      en: "This is the artery a blood-pressure cuff squeezes — the stethoscope listens to it at the crook of your elbow.",
      da: "Det er denne pulsåre, en blodtryksmanchet klemmer sammen — stetoskopet lytter til den i albuebøjningen.",
    },
  },
  {
    id: "femoral-artery",
    layer: "circulatory",
    group: "circulatory",
    at: [186, 508],
    labelSide: "right",
    name: { en: "Femoral artery", da: "Lårpulsåre" },
    latin: "Arteria femoralis",
    description: {
      en: "The great artery of the thigh, carrying blood down the leg. It's wide, close to the surface at the groin and easy for a doctor to reach.",
      da: "Lårets store pulsåre, som fører blod ned gennem benet. Den er bred, ligger tæt på overfladen i lysken og er let for en læge at nå.",
    },
    fact: {
      en: "Heart surgeons often thread a catheter in here and steer it all the way up to the heart.",
      da: "Hjertekirurger fører ofte et kateter ind her og styrer det hele vejen op til hjertet.",
    },
  },
  {
    id: "saphenous",
    layer: "circulatory",
    group: "circulatory",
    at: [190, 720],
    labelSide: "right",
    name: { en: "Great saphenous vein", da: "Den store saphenavene" },
    latin: "Vena saphena magna",
    description: {
      en: "The longest vein in the body, running just under the skin all the way from the foot up the inside of the leg to the groin.",
      da: "Kroppens længste vene, der løber lige under huden hele vejen fra foden op ad benets inderside til lysken.",
    },
    fact: {
      en: "Every step squeezes the calf muscles, which pump blood upwards through this vein against gravity.",
      da: "Hvert skridt klemmer lægmusklerne sammen, og de pumper blodet opad gennem denne vene mod tyngdekraften.",
    },
  },
  {
    id: "capillaries",
    layer: "circulatory",
    group: "circulatory",
    at: [140, 620],
    labelSide: "left",
    name: { en: "Capillaries", da: "Hårkar" },
    latin: "Vasa capillaria",
    description: {
      en: "Vessels so fine that red blood cells pass through in single file. Their walls are one cell thick — thin enough for oxygen and food to slip out to the tissues.",
      da: "Kar så fine, at røde blodlegemer må passere på række. Deres vægge er én celle tykke — tynde nok til, at ilt og næring kan sive ud i vævet.",
    },
    fact: {
      en: "Laid end to end, your capillaries would stretch about 100,000 km — two and a half times around the Earth.",
      da: "Lagt i forlængelse af hinanden ville dine hårkar strække sig cirka 100.000 km — to en halv gang rundt om Jorden.",
    },
  },

  // ───────────────────────── NERVOUS ─────────────────────────
  {
    id: "cerebrum",
    layer: "nervous",
    group: "nervous",
    at: [210, 74],
    labelSide: "right",
    name: { en: "Cerebrum", da: "Storhjerne" },
    latin: "Cerebrum",
    description: {
      en: "The wrinkled outer brain, about 85% of its bulk, split into two halves. Its folded surface is where thinking, speech, memory, and conscious sensation and movement happen.",
      da: "Den rynkede yderhjerne, cirka 85 % af hjernens masse, delt i to halvdele. Dens foldede overflade er der, hvor tanker, sprog, hukommelse og bevidst sansning og bevægelse foregår.",
    },
    fact: {
      en: "The folds triple the surface area. Flattened out, the cortex would cover about the area of a pillowcase.",
      da: "Folderne tredobler overfladen. Foldet ud ville hjernebarken dække omtrent et pudebetræk.",
    },
  },
  {
    id: "cerebellum",
    layer: "nervous",
    group: "nervous",
    at: [232, 116],
    labelSide: "right",
    name: { en: "Cerebellum", da: "Lillehjerne" },
    latin: "Cerebellum",
    description: {
      en: "The 'little brain' tucked under the back of the cerebrum. It smooths and times your movements and keeps you balanced, without you ever thinking about it.",
      da: "Den 'lille hjerne', der ligger under storhjernens bagerste del. Den finjusterer og timer dine bevægelser og holder dig i balance — uden at du tænker over det.",
    },
    fact: {
      en: "It holds over half of all the neurons in your brain, packed into a tenth of its volume.",
      da: "Den rummer over halvdelen af alle hjernens neuroner, presset sammen i en tiendedel af dens rumfang.",
    },
  },
  {
    id: "brainstem",
    layer: "nervous",
    group: "nervous",
    at: [210, 140],
    labelSide: "left",
    name: { en: "Brainstem", da: "Hjernestamme" },
    latin: "Truncus encephali",
    description: {
      en: "The stalk joining brain to spinal cord. It runs the things you never decide to do: heartbeat, breathing, blood pressure, swallowing, coughing and being awake.",
      da: "Stilken, der forbinder hjerne og rygmarv. Den styrer alt det, du aldrig beslutter dig for: hjerteslag, vejrtrækning, blodtryk, synkning, hoste og det at være vågen.",
    },
    fact: {
      en: "It's the reason you keep breathing while you sleep — and the smallest part of the brain you could least afford to lose.",
      da: "Det er derfor, du bliver ved med at trække vejret, mens du sover — og den mindste del af hjernen, du mindst kan undvære.",
    },
  },
  {
    id: "spinal-cord",
    layer: "nervous",
    group: "nervous",
    at: [210, 310],
    labelSide: "right",
    name: { en: "Spinal cord", da: "Rygmarv" },
    latin: "Medulla spinalis",
    description: {
      en: "A cable of nerve tissue about as thick as your little finger, running down inside the spine. Every signal between brain and body below the neck travels through it.",
      da: "Et kabel af nervevæv, cirka så tykt som din lillefinger, der løber ned inde i rygsøjlen. Alle signaler mellem hjernen og kroppen under halsen går gennem den.",
    },
    fact: {
      en: "Some responses never reach the brain at all. Touch something hot and the cord fires the withdrawal itself — you pull back before you feel the pain.",
      da: "Nogle reaktioner når slet ikke hjernen. Rør ved noget varmt, og rygmarven udløser selv tilbagetrækningen — du trækker hånden væk, før du mærker smerten.",
    },
  },
  {
    id: "sciatic-nerve",
    layer: "nervous",
    group: "nervous",
    at: [186, 540],
    labelSide: "right",
    name: { en: "Sciatic nerve", da: "Iskiasnerve" },
    latin: "Nervus ischiadicus",
    description: {
      en: "The thickest and longest nerve in the body, as wide as a thumb where it leaves the pelvis. It runs down the back of the thigh and serves the whole leg below the knee.",
      da: "Kroppens tykkeste og længste nerve, så bred som en tommelfinger hvor den forlader bækkenet. Den løber ned bag på låret og forsyner hele benet under knæet.",
    },
    fact: {
      en: "When a spinal disc presses on its roots, the pain is felt far away down the leg — that's sciatica.",
      da: "Når en diskus trykker på dens rødder, mærkes smerten langt væk nede i benet — det er iskias.",
    },
  },
  {
    id: "brachial-plexus",
    layer: "nervous",
    group: "nervous",
    at: [156, 224],
    labelSide: "left",
    name: { en: "Brachial plexus", da: "Armnervefletning" },
    latin: "Plexus brachialis",
    description: {
      en: "A junction box of nerve roots leaving the neck and rearranging themselves into the main nerves of the arm and hand.",
      da: "En fordelerboks af nerverødder, der forlader halsen og omorganiserer sig til armens og håndens hovednerver.",
    },
    fact: {
      en: "Knock your 'funny bone' and you're actually hitting the ulnar nerve from this plexus where it passes bare over the elbow.",
      da: "Slår du 'musearmen', rammer du i virkeligheden ulnarnerven fra denne fletning, dér hvor den ligger ubeskyttet over albuen.",
    },
  },
  {
    id: "vagus",
    layer: "nervous",
    group: "nervous",
    at: [198, 240],
    labelSide: "left",
    name: { en: "Vagus nerve", da: "Vagusnerve" },
    latin: "Nervus vagus",
    description: {
      en: "The great wandering nerve — its Latin name means 'vagrant'. It leaves the brainstem and roams down to the heart, lungs and gut, calming and regulating as it goes.",
      da: "Den store vandrenerve — dens latinske navn betyder 'omstrejfende'. Den forlader hjernestammen og vandrer ned til hjerte, lunger og tarm og beroliger og regulerer undervejs.",
    },
    fact: {
      en: "It's the main brake on your heart rate. Slow, deep breathing works on your pulse through this nerve.",
      da: "Den er hovedbremsen på din puls. Langsom, dyb vejrtrækning virker på pulsen gennem netop denne nerve.",
    },
  },

  // ──────────────────────── LYMPHATIC ────────────────────────
  {
    id: "lymph-nodes-cervical",
    layer: "lymphatic",
    group: "lymphatic",
    at: [192, 180],
    labelSide: "left",
    name: { en: "Neck lymph nodes", da: "Lymfeknuder på halsen" },
    latin: "Nodi lymphoidei cervicales",
    description: {
      en: "Small filters strung along the lymph vessels of the neck. White blood cells inside them trap and destroy germs travelling in the lymph fluid.",
      da: "Små filtre på rad langs halsens lymfekar. Hvide blodlegemer inde i dem fanger og ødelægger bakterier, der rejser med lymfevæsken.",
    },
    fact: {
      en: "The tender lumps in your neck during a sore throat are these nodes, swollen because they're busy fighting.",
      da: "De ømme knuder på halsen ved ondt i halsen er netop disse knuder — hævede, fordi de har travlt med at kæmpe.",
    },
  },
  {
    id: "lymph-nodes-axillary",
    layer: "lymphatic",
    group: "lymphatic",
    at: [148, 252],
    labelSide: "left",
    name: { en: "Armpit lymph nodes", da: "Lymfeknuder i armhulen" },
    latin: "Nodi lymphoidei axillares",
    description: {
      en: "A cluster of twenty to forty nodes in each armpit, draining lymph from the arm, chest wall and breast.",
      da: "En klynge på tyve til fyrre knuder i hver armhule, som dræner lymfe fra arm, brystvæg og bryst.",
    },
    fact: {
      en: "Because breast lymph drains here first, these are the nodes doctors check when staging breast cancer.",
      da: "Fordi brystets lymfe drænes hertil først, er det disse knuder, læger undersøger, når brystkræft stadieinddeles.",
    },
  },
  {
    id: "thymus",
    layer: "lymphatic",
    group: "lymphatic",
    at: [210, 258],
    labelSide: "right",
    name: { en: "Thymus", da: "Brissel" },
    latin: "Thymus",
    description: {
      en: "A gland behind the breastbone where T-lymphocytes — the immune system's coordinators — are trained to tell your own cells from invaders.",
      da: "En kirtel bag brystbenet, hvor T-lymfocytter — immunforsvarets koordinatorer — trænes i at skelne dine egne celler fra fjender.",
    },
    fact: {
      en: "It's largest in childhood and slowly shrinks after puberty. Most of your immune training happened before you were ten.",
      da: "Den er størst i barndommen og skrumper langsomt efter puberteten. Det meste af din immuntræning skete, før du fyldte ti.",
    },
  },
  {
    id: "lymph-nodes-inguinal",
    layer: "lymphatic",
    group: "lymphatic",
    at: [178, 476],
    labelSide: "left",
    name: { en: "Groin lymph nodes", da: "Lymfeknuder i lysken" },
    latin: "Nodi lymphoidei inguinales",
    description: {
      en: "The collecting station for lymph returning from the legs, and the last filter before that fluid rejoins the bloodstream.",
      da: "Opsamlingsstationen for lymfe på vej tilbage fra benene og det sidste filter, før væsken igen når blodbanen.",
    },
    fact: {
      en: "Lymph has no pump. It's squeezed along entirely by the muscles you move and by breathing.",
      da: "Lymfen har ingen pumpe. Den presses udelukkende frem af de muskler, du bevæger, og af vejrtrækningen.",
    },
  },
  {
    id: "thoracic-duct",
    layer: "lymphatic",
    group: "lymphatic",
    at: [200, 330],
    labelSide: "left",
    name: { en: "Thoracic duct", da: "Brystgangen" },
    latin: "Ductus thoracicus",
    description: {
      en: "The main lymph highway. It gathers lymph from the legs, abdomen and left side of the body and empties it back into a large vein near the left collarbone.",
      da: "Lymfens hovedvej. Den samler lymfe fra ben, mave og kroppens venstre side og tømmer den tilbage i en stor vene nær venstre kraveben.",
    },
    fact: {
      en: "Around 3 litres of fluid leak out of your capillaries into the tissues each day. This duct is how nearly all of it gets home.",
      da: "Cirka 3 liter væske siver hver dag ud af hårkarrene og ud i vævet. Denne gang er vejen hjem for næsten det hele.",
    },
  },

  // ──────────────────────── ENDOCRINE ────────────────────────
  {
    id: "pituitary",
    layer: "endocrine",
    group: "endocrine",
    at: [210, 110],
    labelSide: "right",
    name: { en: "Pituitary gland", da: "Hypofyse" },
    latin: "Hypophysis",
    description: {
      en: "A pea-sized gland hanging beneath the brain. It releases hormones that command the other glands — which is why it's called the master gland.",
      da: "En ærtestor kirtel, der hænger under hjernen. Den udskiller hormoner, som kommanderer de andre kirtler — derfor kaldes den overkirtlen.",
    },
    fact: {
      en: "One of its hormones controls how tall you grow. It is roughly the size and weight of a small pea.",
      da: "Et af dens hormoner styrer, hvor høj du bliver. Den er omtrent på størrelse og vægt med en lille ært.",
    },
  },
  {
    id: "thyroid",
    layer: "endocrine",
    group: "endocrine",
    at: [210, 196],
    labelSide: "left",
    name: { en: "Thyroid gland", da: "Skjoldbruskkirtel" },
    latin: "Glandula thyroidea",
    description: {
      en: "A butterfly-shaped gland wrapped around the windpipe. Its hormones set the speed of your metabolism — how fast every cell in the body burns fuel.",
      da: "En sommerfugleformet kirtel, der ligger om luftrøret. Dens hormoner sætter tempoet for dit stofskifte — hvor hurtigt hver eneste celle forbrænder brændstof.",
    },
    fact: {
      en: "It needs iodine to work, which is why iodine is added to table salt in many countries.",
      da: "Den har brug for jod for at fungere — derfor tilsættes jod til køkkensalt i mange lande.",
    },
  },
  {
    id: "adrenals",
    layer: "endocrine",
    group: "endocrine",
    at: [180, 368],
    labelSide: "left",
    name: { en: "Adrenal glands", da: "Binyrer" },
    latin: "Glandulae suprarenales",
    description: {
      en: "Two small caps sitting on top of the kidneys. They release adrenaline for emergencies and cortisol for longer-running stress and daily rhythm.",
      da: "To små hætter, der sidder oven på nyrerne. De udskiller adrenalin ved fare og kortisol ved længerevarende stress og til døgnrytmen.",
    },
    fact: {
      en: "A jolt of adrenaline reaches your heart in a couple of seconds — faster than a nerve message could travel and be acted on.",
      da: "Et gys adrenalin når dit hjerte på et par sekunder — hurtigere end en nervebesked kunne nå frem og virke.",
    },
  },
  {
    id: "pancreas-islets",
    layer: "endocrine",
    group: "endocrine",
    at: [236, 380],
    labelSide: "right",
    name: { en: "Islets of Langerhans", da: "Langerhanske øer" },
    latin: "Insulae pancreaticae",
    description: {
      en: "About a million clumps of hormone cells scattered through the pancreas. They release insulin when blood sugar rises and glucagon when it falls.",
      da: "Omkring en million klumper af hormonceller spredt i bugspytkirtlen. De frigiver insulin, når blodsukkeret stiger, og glukagon, når det falder.",
    },
    fact: {
      en: "They hold your blood sugar in a narrow band all day long, whatever and whenever you eat.",
      da: "De holder dit blodsukker inden for et snævert bånd hele dagen — uanset hvad og hvornår du spiser.",
    },
  },
  {
    id: "hypothalamus",
    layer: "endocrine",
    group: "endocrine",
    at: [196, 100],
    labelSide: "left",
    name: { en: "Hypothalamus", da: "Hypothalamus" },
    latin: "Hypothalamus",
    description: {
      en: "An almond-sized region above the pituitary where the nervous and hormone systems meet. It governs temperature, thirst, hunger, sleep and the daily body clock.",
      da: "Et mandelstort område over hypofysen, hvor nervesystemet og hormonsystemet mødes. Det styrer temperatur, tørst, sult, søvn og døgnrytmen.",
    },
    fact: {
      en: "It holds your core temperature within a few tenths of a degree of 37°C, year-round.",
      da: "Det holder din kernetemperatur inden for få tiendedele af en grad omkring 37 °C, året rundt.",
    },
  },
];

export function structuresFor(sex: Sex): Structure[] {
  return STRUCTURES.filter((s) => !s.sex || s.sex === sex);
}

export function structureById(id: string): Structure | undefined {
  return STRUCTURES.find((s) => s.id === id);
}
